#!/bin/bash
#ANTHONY PORPORINO
#260863300

#Make sure user inputed correct number of arguments
if [ $# != 2 ]; 
then
	echo “Error: Wrong number of arguments. Please type ./mkproj ARGUMENT OWNER. The argument is the name of the project. The OWNER is the user name the project belongs to.”
	exit 1	#Terminate the script with exit code 1 for failure
fi

#Check to see if Projects directory exists already
if [ ! -d "Projects" ]; 
then
	mkdir Projects
fi
cd Projects

#Check if project name is already taken
if [ -d $1 ]; 
then
	echo “Error: The project name has already been used. Please select another project name and try again.”
	cd ..
	exit 2	#Terminate program with exit status 2
fi

#Make project dir with all sub directories
mkdir $1
cd $1
mkdir archive
mkdir backup
mkdir docs
mkdir assets
mkdir database
mkdir source
ls
cd docs

#Create readme file and echo text to it
touch readme.txt
echo “Created by: $2” >> readme.txt
cat readme.txt
